### PR TITLE
All BUGS worked out and Develop Finalized

### PR DESCRIPTION
**Pull request by ErikPlachta**
## The team has fully reviewed everything and verified integrity. Pushing to Main!

### CODE REVIEW

**Review by ErikPlachta — COMMENTED** [review]
Reviewed everything and it looks good!

**Review by barrantesc — APPROVED** [review]
Looks great!

**Review by NicaVulcan — APPROVED** [review]

**Comment by mmlawton15** [comment]
looks awesome!

**Comment by mmlawton15** [comment]
my slack is not working, can i close this?

**Review by mmlawton15 — COMMENTED** [review]
looks amaze

**Review by mmlawton15 — APPROVED** [review]

**Pull request merged**
