### PR TITLE
Add Feature: ORM: Model Framework Built

### PR DESCRIPTION
**Pull request by NicaVulcan**
## @mmlawton15  Built framework for ORM related to #15 which was a required first step. Now that this is done we can build #20 

 
-@ErikPlachta 

---

### Framed out Model Content

- [x] User Model
- [x] Character model

```
//-- users is logging into our app
user = {
id
username
email
password
}

//-- Characters is created by users logged into app
character = {
id,
user_id
name
race
class
gender
}
```

### CODE REVIEW

**Review by NicaVulcan — COMMENTED** [review]
!!

**Review by barrantesc — APPROVED** [review]

**Review by ErikPlachta — COMMENTED** [review]
Nice work @mmlawton15 thank you for focusing on this 2nite.

**Review by ErikPlachta — APPROVED** [review]

**Comment by barrantesc** [comment]
Do we need to ask the user to create an username as we are only requiring the email address at log in? or is this username only for the user + have it show when user logs in?

**Review by mmlawton15 — APPROVED** [review]
good

**Comment by ErikPlachta** [comment]
> Do we need to ask the user to create an username as we are only requiring the email address at log in? or is this username only for the user + have it show when user logs in?

We haven't decided yet, @barrantesc

**Pull request merged**
