### PR TITLE
Phase 1 of ALL Develop is completed!

### PR DESCRIPTION
**Pull request by ErikPlachta**
### https://sheet-show.herokuapp.com/

### CODE REVIEW

**Review by mmlawton15 — APPROVED** [review]
looks great! woo!

**Review by NicaVulcan — APPROVED** [review]

**Comment by barrantesc** [comment]
Looks great! :D

**Review by barrantesc — COMMENTED** [review]
great!

**Review by barrantesc — APPROVED** [review]
Looks great!

**Pull request merged**
