### PR TITLE
Initial commit with base content that needs to be udpated

### PR DESCRIPTION
**Pull request by ErikPlachta**
## I built the basic framework so we can have a place to start

### CODE REVIEW

**Review by barrantesc — APPROVED** [review]

**Review by ErikPlachta — COMMENTED** [review]
Basic framework is all good. Lots will need to be updated cleaned up, etc

**Review by NicaVulcan — COMMENTED** [review]
good to go!

**Comment by barrantesc** [comment]
Good !

**Review by barrantesc — APPROVED** [review]

**Review by ErikPlachta — COMMENTED** [review]
Good

**Review by NicaVulcan — COMMENTED** [review]
Good to go!

**Review by mmlawton15 — APPROVED** [review]
mldsfgkjjsdfgja

**Review by NicaVulcan — APPROVED** [review]

**Pull request merged**
